# .github/workflows/docker-build.yml
name: Build and Push Container

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker Tags
        id: prep
        run: |
          REPO=${GITHUB_REPOSITORY,,}  # Convert to lowercase
          echo "DOCKER_IMAGE=ghcr.io/${REPO}" >> $GITHUB_ENV
          echo "TAGS=${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64